language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "4"
  - "iojs"
before_install:
  - 'nvm install-latest-npm'
before_script:
  - 'if [ -n "${KARMA-}" ]; then export DISPLAY=:99.0; fi'
  - 'if [ -n "${KARMA-}" ]; then sh -e /etc/init.d/xvfb start; fi'
  - 'if [ -n "${KARMA-}" ]; then sleep 3; fi'
script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ "${TEST-}" = true ]; then npm run tests-only ; fi'
  - 'if [ -n "${KARMA-}" ]; then npm run tests-karma ; fi'
  - 'if [ -n "${COVERAGE-}" ] && [ "${TRAVIS_BRANCH-}" = "master" ]; then npm run cover; cat ./coverage/lcov.info | ./node_modules/.bin/coveralls ; fi'
env:
  global:
    - TEST=true
  matrix:
    - REACT=0.14
    - REACT=15
    - REACT=16
sudo: false
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: COVERAGE=true TEST=false
    - node_js: "lts/*"
      env: KARMA=true TEST=false
    - node_js: "lts/*"
      env: LINT=true TEST=false
  allow_failures:
    - node_js: "9"
    - node_js: "7"
    - node_js: "iojs"
    - env: KARMA=true TEST=false
